var OEM = {
	PRODUCT_EN: "",
	PRODUCT_CN: "自写UI组件",
	VERSION_MAJOR: "",
	VERSION_MINOR: "",
	VERSION_REV: "",
	VERSION_BUILD: "",
	VERSION_STRING: "",
	COMPANY_BRAND: "",
	COMPANY_NAME: "",
	COMPANY_URL: "",
	COMPANY_PHONE: "",
	COMPANY_EMAIL: "",
	PRODUCT_URL: "",
	VERSION: "",
	COPY_RIGHT: ""
};


